export const APIConstant = {
    LOGIN:{
        GET_LOGIN:'User/login'
    },
    MASTER:{
        GET_ALL_MASTER:'Master/get-all-masters',
        CREATE_NEW_MASTER:'Master/create-master',
        UPDATE_MASTER:'Master/update-master/',
        DELETE_MASTER:'Master/delete-master/',
        GET_ALL_FILTER_MASTER:'Master/get-masters-by-type/'
    },
    PACKAGE:{
        GET_ALL_PACKAGES:'PackageMaster/get-all-packages',
        CREATE_NEW_PACKAGES:'PackageMaster/create-package',
        UPDATE_PACKAGES:'PackageMaster/update-package/',
        DELETE_PACKAGES:'PackageMaster/delete-package/',
        GET_ALL_FILTER_PACKAGES_BY_ID:'/PackageMaster/get-package-by-id/'
    },
    INSTITUTE:{
        GET_ALL_INSTITUTE:'InstituteMaster/get-all-institutes',
        CREATE_NEW_INSTITUTE:'InstituteMaster/create-institute',
        UPDATE_INSTITUTE:'InstituteMaster/update-institute/',
        DELETE_INSTITUE:'InstituteMaster/delete-institute/',
        GET_ALL_FILTER_INSTITUTE_BY_ID:'InstituteMaster/get-institute-by-id/'
    }
}